import type { ScholarshipData } from "@/types/scholarship"
import { CONTACT } from "@/types/scholarship"

export const SCHOLARSHIPS: ScholarshipData[] = [
  // ─── BACHELOR ───────────────────────────────────────────────────────────────

  {
    id: "hengyang-bachelor-01",
    title: "Bachelor Scholarship – Hengyang",
    level: "BACHELOR",
    country: "China",
    city: "Hengyang",
    intake: "September 2026",
    duration: "4 Years",
    language: "English",
    ageRange: "18–25",
    overview: "4-year Bachelor scholarship at a university in Hengyang, near Guangzhou. Designed for international students seeking quality engineering education in China with a partially subsidized tuition package and no CSCA requirement.",
    majors: [
      "Civil Engineering",
      "Software Engineering",
      "Mechanical Design, Manufacture & Automation",
    ],
    financials: {
      tuition: "7,500 RMB/year (subsidized)",
      accommodation: "3,000–5,000 RMB/year",
      registrationFee: "6,600 RMB (one-time)",
      deposit: "1,000 RMB (refundable)",
      notes: [
        "Registration fee paid before admission letter is issued",
        "Deposit refunded upon arrival at university",
      ],
    },
    requirements: {
      eligibility: [
        "Age 18–25",
        "Open to all nationalities",
        "No CSCA (Chinese Scholarship Council Application) required",
        "Secondary school certificate or equivalent",
      ],
      documents: [
        "Valid passport (6+ months validity)",
        "Academic certificates (secondary school)",
        "Official transcripts",
        "Bank statement (proof of funds)",
        "Passport-size ID photo",
        "Video introduction (1–2 minutes)",
        "Non-criminal record certificate",
      ],
    },
    applicationHighlights: [
      "No CSCA required — simpler application process",
      "Subsidized tuition — lower annual cost",
      "English-medium instruction — no Chinese required",
      "International applicants accepted worldwide",
    ],
    admissionProcess: [
      "Submit application with required documents",
      "Admin team reviews within 48 hours",
      "Pre-admission offer letter issued",
      "Registration fee payment confirmed",
      "Final admission letter & visa support",
    ],
    contact: CONTACT,
    tags: ["engineering", "bachelor", "hengyang", "scholarship", "no-csca"],
    isFeatured: true,
    sortOrder: 10,
  },

  {
    id: "zhejiang-bachelor-a",
    title: "Bachelor Program – Zhejiang (Option A)",
    level: "BACHELOR",
    country: "China",
    city: "Zhejiang",
    intake: "September 2026",
    duration: "4 Years",
    language: "English",
    ageRange: "18–25",
    overview: "Study in Zhejiang province — close to Yiwu, Hangzhou and Shanghai — with partial scholarship support. Option A offers a broad range of majors across business, technology, and sciences with refundable first-year tuition.",
    majors: [
      "E-Commerce",
      "Tourism Management",
      "Computer Science & Technology",
      "Civil Engineering",
      "English Language & Literature",
      "Horticulture",
      "New Energy Materials & Devices",
    ],
    financials: {
      tuition: "Year 1: 9,000 RMB (refundable upon graduation)",
      accommodation: "1,750 RMB/year",
      registrationFee: "6,800 RMB (one-time)",
      deposit: "9,400 RMB seat reservation fee",
      notes: [
        "Year 1 tuition is refundable at end of program",
        "Seat deposit secures your admission slot",
        "Partial scholarship offsets remaining costs",
      ],
    },
    requirements: {
      eligibility: [
        "Age 18–25",
        "English-medium instruction track",
        "Minimum secondary school qualification",
      ],
      documents: [
        "Valid passport",
        "Academic certificates",
        "Official transcripts",
        "Bank statement",
        "Passport-size photo",
      ],
    },
    applicationHighlights: [
      "Refundable first-year tuition",
      "Partial scholarship support available",
      "Located near Yiwu trade hub and Hangzhou tech city",
      "Broad major selection — business, tech, sciences",
    ],
    admissionProcess: [
      "Apply online with documents",
      "Document review & verification",
      "Pre-admission offer issued",
      "Pay seat deposit to confirm",
      "Admission letter & visa processing",
    ],
    contact: CONTACT,
    tags: ["zhejiang", "bachelor", "business", "technology", "e-commerce"],
    sortOrder: 20,
  },

  {
    id: "zhejiang-bachelor-b",
    title: "Bachelor Program – Zhejiang (Option B)",
    level: "BACHELOR",
    country: "China",
    city: "Zhejiang",
    intake: "September 2026",
    duration: "4 Years",
    language: "English",
    ageRange: "18–25",
    overview: "Option B at the same Zhejiang institution offers specialized majors in pharmacy, economics, and arts. Suitable for students with interests in life sciences, international trade, or music.",
    majors: [
      "Biological Pharmacy",
      "International Economics & Trade",
      "Musicology",
    ],
    financials: {
      tuition: "Year 1: 9,000 RMB (refundable upon graduation)",
      accommodation: "1,750 RMB/year",
      registrationFee: "6,800 RMB (one-time)",
      deposit: "9,400 RMB seat reservation fee",
      notes: [
        "Same fee structure as Option A",
        "Partial scholarship available for qualifying applicants",
      ],
    },
    requirements: {
      eligibility: [
        "Age 18–25",
        "English-medium instruction",
        "Relevant secondary school background preferred",
      ],
      documents: [
        "Valid passport",
        "Academic certificates",
        "Official transcripts",
        "Bank statement",
        "Passport-size photo",
      ],
    },
    applicationHighlights: [
      "Specialized pharmacy & sciences track",
      "International economics pathway",
      "Musicology program — rare in Africa-China admissions",
      "Same refundable tuition as Option A",
    ],
    admissionProcess: [
      "Apply online with documents",
      "Document review & verification",
      "Pre-admission offer issued",
      "Pay seat deposit to confirm",
      "Admission letter & visa processing",
    ],
    contact: CONTACT,
    tags: ["zhejiang", "bachelor", "pharmacy", "economics", "musicology"],
    sortOrder: 30,
  },

  {
    id: "hangzhou-bachelor-01",
    title: "Bachelor Scholarship – Hangzhou",
    level: "BACHELOR",
    country: "China",
    city: "Hangzhou",
    intake: "September 2026",
    duration: "4 Years",
    language: "English",
    ageRange: "18–25",
    overview: "Top 180 QS-ranked university in Hangzhou — China's digital economy capital. Scholarship of 10,000 RMB/year with no CSCA requirement. Strong programs in digital economy, technology, and business.",
    majors: [
      "Digital Economy",
      "Computer Science & Technology",
      "Software Engineering",
      "Business Administration",
      "International Trade",
      "Finance",
      "Data Science",
    ],
    financials: {
      tuition: "18,000 RMB/year (standard)",
      accommodation: "4,000–6,000 RMB/year",
      registrationFee: "7,500 RMB (one-time)",
      stipend: "10,000 RMB/year scholarship offset",
      notes: [
        "Scholarship of 10,000 RMB/year reduces effective tuition to 8,000 RMB/year",
        "No CSCA required",
        "Top 180 QS World University Rankings",
      ],
    },
    requirements: {
      eligibility: [
        "Age 18–25",
        "Minimum GPA equivalent of B+ or above",
        "English proficiency (IELTS 5.5+ or equivalent)",
        "No CSCA required",
      ],
      documents: [
        "Valid passport",
        "Secondary school certificate",
        "Official transcripts",
        "English proficiency certificate (if available)",
        "Bank statement",
        "Photo",
        "Personal statement",
      ],
    },
    applicationHighlights: [
      "Top 180 global university ranking",
      "10,000 RMB/year scholarship for all admitted students",
      "No CSCA — faster application process",
      "Located in Hangzhou — home of Alibaba & digital innovation",
    ],
    admissionProcess: [
      "Submit application & documents",
      "48-hour admin review",
      "Pre-admission offer with scholarship confirmation",
      "Registration fee payment",
      "Final admission letter & visa support",
    ],
    contact: CONTACT,
    tags: ["hangzhou", "bachelor", "digital-economy", "top-university", "scholarship", "technology"],
    isFeatured: true,
    sortOrder: 5,
  },

  {
    id: "shanghai-bachelor-01",
    title: "Bachelor Program – Shanghai",
    level: "BACHELOR",
    country: "China",
    city: "Shanghai",
    intake: "September 2026",
    duration: "4 Years",
    language: "English",
    ageRange: "18–25",
    overview: "Study in Shanghai — China's financial and commercial capital. Two funding tracks available: Type A (partial scholarship) and Type B (self-funded with accommodation subsidy). Strong programs in engineering and business.",
    majors: [
      "Automation",
      "Software Engineering",
      "Marketing",
      "International Business",
      "Mechanical Engineering",
      "Electrical Engineering",
    ],
    financials: {
      tuition: "Type A: 12,000 RMB/year | Type B: 18,000 RMB/year",
      accommodation: "5,000–8,000 RMB/year",
      registrationFee: "8,000 RMB (one-time)",
      deposit: "2,000 RMB (refundable)",
      notes: [
        "Type A: partial scholarship — 6,000 RMB/year deducted",
        "Type B: self-funded, accommodation subsidy of 2,000 RMB/year",
        "Shanghai cost of living is higher — budget accordingly",
      ],
    },
    requirements: {
      eligibility: [
        "Age 18–25",
        "Minimum B grade average in secondary school",
        "English proficiency preferred",
      ],
      documents: [
        "Valid passport",
        "Academic certificates",
        "Official transcripts",
        "Bank statement (min. 30,000 RMB equivalent)",
        "Photo",
        "Personal statement",
        "Non-criminal record",
      ],
    },
    applicationHighlights: [
      "Two funding options — Type A or Type B",
      "Located in Shanghai — China's #1 business hub",
      "Strong industry connections and internship access",
      "English-medium instruction",
    ],
    admissionProcess: [
      "Choose funding type (A or B)",
      "Submit application with documents",
      "Document verification (48h)",
      "Pre-admission & funding confirmation",
      "Registration fee payment",
      "Admission letter & visa support",
    ],
    contact: CONTACT,
    tags: ["shanghai", "bachelor", "engineering", "business", "type-a", "type-b"],
    sortOrder: 15,
  },

  // ─── MASTER ─────────────────────────────────────────────────────────────────

  {
    id: "jiangsu-master-01",
    title: "Master Scholarship – Jiangsu (Top 80 University)",
    level: "MASTER",
    country: "China",
    city: "Jiangsu",
    intake: "September 2026",
    duration: "2–3 Years",
    language: "English",
    ageRange: "22–35",
    overview: "Top 80 QS-ranked university in Jiangsu province. Covers medicine, engineering, and business fields. Comprehensive scholarship with multi-discipline major tracks and strong research facilities.",
    majors: [
      // Medical
      "Clinical Medicine", "Public Health", "Pharmacology", "Biomedical Engineering",
      // Engineering
      "Civil Engineering", "Computer Science", "Electrical Engineering", "Mechanical Engineering",
      // Business
      "Business Administration (MBA)", "International Trade", "Finance", "Economics",
    ],
    financials: {
      tuition: "Full tuition waiver",
      accommodation: "4,500 RMB/year (campus dormitory)",
      registrationFee: "8,500 RMB (one-time)",
      stipend: "2,500 RMB/month living allowance",
      notes: [
        "Tuition fully covered by scholarship",
        "Monthly stipend of 2,500 RMB provided",
        "Top 80 global ranking — competitive admissions",
      ],
    },
    requirements: {
      eligibility: [
        "Bachelor's degree (minimum 2nd class upper or equivalent)",
        "Age 22–35",
        "IELTS 6.0+ or equivalent English proficiency",
        "GPA 3.0/4.0 or above",
      ],
      documents: [
        "Valid passport",
        "Bachelor's degree certificate",
        "Official university transcripts",
        "English proficiency certificate (IELTS/TOEFL)",
        "Personal statement / research proposal",
        "Two recommendation letters",
        "CV / resume",
        "Medical certificate",
        "Non-criminal record",
        "Bank statement",
        "Photo",
      ],
      extraInfo: [
        "Research proposal required for PhD track applicants",
        "Interview may be required for medical programs",
      ],
    },
    applicationHighlights: [
      "Top 80 QS World University Ranking",
      "Full tuition waiver",
      "2,500 RMB/month living stipend",
      "Multi-discipline tracks: Medical, Engineering, Business",
      "48-hour application response guarantee",
    ],
    admissionProcess: [
      "Submit application with all documents",
      "48-hour admin review & feedback",
      "University conditional offer issued",
      "Registration fee payment",
      "Scholarship confirmation letter",
      "Final admission letter & visa support",
    ],
    contact: CONTACT,
    tags: ["jiangsu", "master", "medicine", "engineering", "business", "top-university", "scholarship"],
    isFeatured: true,
    sortOrder: 40,
  },

  {
    id: "tsinghua-master-01",
    title: "Tsinghua University Master Program",
    level: "MASTER",
    country: "China",
    city: "Beijing",
    intake: "September 2026",
    duration: "2 Years",
    language: "English",
    ageRange: "22–32",
    overview: "Fully funded master's program at Tsinghua University — China's #1 university. Only 5 slots available. Covers tuition, accommodation, and provides a 3,000 RMB/month stipend. Highly competitive, 48-hour response guarantee.",
    majors: [
      "Computer Science & Technology",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil & Environmental Engineering",
      "Economics & Finance",
      "Public Policy & Management",
    ],
    financials: {
      tuition: "Fully funded (100% tuition waiver)",
      accommodation: "Fully funded (on-campus housing)",
      stipend: "3,000 RMB/month",
      registrationFee: "9,500 RMB (one-time admin fee)",
      notes: [
        "Only 5 slots available — first-come, first-served",
        "3,000 RMB/month is the highest stipend in our network",
        "Tsinghua is ranked #1 in Asia, Top 25 globally",
        "48-hour response guarantee from our team",
      ],
    },
    requirements: {
      eligibility: [
        "Exceptional academic record (minimum GPA 3.5/4.0)",
        "Age 22–32",
        "IELTS 6.5+ or TOEFL 90+",
        "Relevant Bachelor's degree",
        "Strong motivation letter required",
      ],
      documents: [
        "Valid passport",
        "Bachelor's degree certificate",
        "Official transcripts (translated if needed)",
        "IELTS/TOEFL certificate",
        "Motivation letter (minimum 800 words)",
        "Two strong recommendation letters",
        "Detailed CV",
        "Research interest statement",
        "Medical certificate",
        "Non-criminal record",
        "Photo",
      ],
      extraInfo: [
        "Only 5 slots — apply immediately",
        "Video interview required for shortlisted candidates",
        "Strong research statement increases acceptance chance",
      ],
    },
    applicationHighlights: [
      "Tsinghua University — #1 in Asia",
      "Fully funded — tuition + housing + 3,000 RMB/month",
      "Only 5 slots available",
      "48-hour review guarantee from EA Trade Link team",
    ],
    admissionProcess: [
      "Submit complete application urgently (5 slots only)",
      "EA Trade Link review within 48 hours",
      "Tsinghua application submitted on your behalf",
      "Interview scheduling for shortlisted candidates",
      "Offer letter & scholarship confirmation",
      "Visa support & pre-departure guidance",
    ],
    contact: CONTACT,
    tags: ["tsinghua", "beijing", "master", "fully-funded", "top-university", "prestigious", "limited-slots"],
    isFeatured: true,
    slots: 5,
    sortOrder: 45,
  },

  {
    id: "zhejiang-medical-master-01",
    title: "Medical Master Program – Zhejiang",
    level: "MASTER",
    country: "China",
    city: "Zhejiang",
    intake: "September 2026",
    duration: "3 Years",
    language: "English",
    ageRange: "22–35",
    overview: "100% tuition-free medical master's program at a Zhejiang medical university. Specialized clinical tracks across major medical disciplines. Ideal for graduates with a medical or health sciences background.",
    majors: [
      "Clinical Medicine",
      "Internal Medicine",
      "Surgery",
      "Pediatrics",
      "Obstetrics & Gynecology",
      "Pharmacology",
      "Public Health & Epidemiology",
      "Biomedical Engineering",
      "Traditional Chinese Medicine",
      "Nursing Science",
    ],
    financials: {
      tuition: "100% free (full tuition scholarship)",
      accommodation: "3,500 RMB/year",
      registrationFee: "7,800 RMB (one-time)",
      stipend: "1,500 RMB/month",
      notes: [
        "Tuition completely waived for all admitted students",
        "Monthly stipend covers basic living expenses",
        "Medical simulation labs and hospital attachments included",
      ],
    },
    requirements: {
      eligibility: [
        "Bachelor's degree in Medicine, Health Sciences, or Pharmacy",
        "Age 22–35",
        "English proficiency (IELTS 6.0+ preferred)",
        "Internship/clinical experience preferred",
      ],
      documents: [
        "Valid passport",
        "Medical degree certificate",
        "Official transcripts",
        "Clinical experience certificate (if applicable)",
        "English proficiency certificate",
        "Personal statement",
        "Two recommendation letters (from medical professionals)",
        "Medical certificate",
        "Non-criminal record",
        "Photo",
      ],
    },
    applicationHighlights: [
      "100% tuition-free — zero tuition cost",
      "10 clinical specializations to choose from",
      "Hospital attachment and clinical rotations",
      "1,500 RMB/month stipend",
    ],
    admissionProcess: [
      "Submit application with medical credentials",
      "Medical background verification (48h)",
      "Conditional offer issued",
      "Registration fee payment",
      "Scholarship and tuition waiver confirmation",
      "Admission letter & visa support",
    ],
    contact: CONTACT,
    tags: ["zhejiang", "master", "medicine", "clinical", "fully-funded-tuition", "medical"],
    sortOrder: 50,
  },

  // ─── PhD ─────────────────────────────────────────────────────────────────────

  {
    id: "global-phd-01",
    title: "Global PhD Scholarship – China",
    level: "PHD",
    country: "China",
    city: "Multiple Cities",
    intake: "September 2026",
    duration: "3–4 Years",
    language: "English",
    ageRange: "24–40",
    overview: "Fully funded PhD scholarship across top Chinese universities. Covers tuition, accommodation, and a 3,500 RMB monthly research stipend. Available in Medical, Engineering, and Governance tracks. Research proposal required. 48-hour review system.",
    majors: [
      // Medical
      "Clinical Medicine", "Public Health", "Pharmacology", "Biomedical Engineering",
      // Engineering
      "Computer Science", "Electrical Engineering", "Civil Engineering",
      "Environmental Engineering", "Artificial Intelligence",
      // Governance & Social Sciences
      "Public Policy", "International Relations", "Development Economics",
      "Environmental Studies", "Educational Leadership",
    ],
    financials: {
      tuition: "Fully funded (100% tuition waiver)",
      accommodation: "Fully funded (campus housing provided)",
      stipend: "3,500 RMB/month research stipend",
      registrationFee: "10,000 RMB (one-time)",
      notes: [
        "3,500 RMB/month stipend for the full program duration",
        "Research conference travel support available",
        "University varies by major and ranking preference",
        "48-hour initial review from our team",
      ],
    },
    requirements: {
      eligibility: [
        "Master's degree in relevant field",
        "Age 24–40",
        "IELTS 6.5+ or TOEFL 90+ (English track)",
        "Strong research background",
        "Publications preferred but not mandatory",
      ],
      documents: [
        "Valid passport",
        "Master's degree certificate",
        "Official transcripts (Bachelor + Master)",
        "Research proposal (2,000–5,000 words)",
        "English proficiency certificate",
        "Detailed CV with publications list",
        "Three recommendation letters",
        "Personal motivation statement",
        "Medical certificate",
        "Non-criminal record",
        "Photo",
      ],
      extraInfo: [
        "Research proposal is the most critical document",
        "Propose a supervisor from target university if possible",
        "Interview required for all shortlisted candidates",
        "Publications boost admission probability significantly",
      ],
    },
    applicationHighlights: [
      "Fully funded — tuition, housing, and 3,500 RMB/month",
      "3 research tracks: Medical, Engineering, Governance",
      "Multiple top-ranked Chinese universities",
      "48-hour review guarantee from EA Trade Link",
    ],
    admissionProcess: [
      "Prepare and submit research proposal",
      "EA Trade Link review within 48 hours",
      "University selection & supervisor matching",
      "Formal application submitted to university",
      "Interview with academic supervisor",
      "Scholarship & admission confirmation",
      "Visa support & pre-departure preparation",
    ],
    contact: CONTACT,
    tags: ["phd", "fully-funded", "research", "medicine", "engineering", "governance", "stipend"],
    isFeatured: true,
    sortOrder: 60,
  },
]

export function getScholarshipById(id: string): ScholarshipData | undefined {
  return SCHOLARSHIPS.find((s) => s.id === id)
}
